enableGlobalCache: false

nodeLinker: pnp
enableScripts: false
packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-webpack5": ^7.2.2

yarnPath: .yarn/releases/yarn-4.1.1.cjs