export const PATH = {
  ROOT: "/",
  SIREN: "/siren",
  SIREN_DETAIL: (sirenId: string) => `/siren/${sirenId}`,
  SIREN_EDIT: (sirenId: string) => `/siren/${sirenId}?mode=edit`,
  SIREN_UPLOAD: "/siren-new",
  QUESTION: "/question",
  QUESTION_DETAIL: (questionId: string) => `/question/${questionId}`,
  QUESTION_EDIT: (questionId: string) => `/question/${questionId}?mode=edit`,
  QUESTION_UPLOAD: "/question-new",
  MY: (userUrl: string) => `/${userUrl}`,
  AUTH: "/auth",
  SIGN_UP: "/signup",
  CONNECTION: "/connection",
  RELOAD: 0,
  TEAM_CREATE: "/team/create",
  TEAM_EDIT: (teamId: ":teamId" | number) => `/team/${teamId}/edit`,
  PLANNING: "/planning",
} as const;
